from typing import Any, AsyncIterable, Callable, List, Tuple

from dreaming_electric_sheep.contents import Content, ServerSentEvent
from dreaming_electric_sheep.cookies import Cookie
from dreaming_electric_sheep.messages import Request, Response

def write_chunks(content: Content) -> AsyncIterable[bytes]: ...
async def send_asgi_response(response: Response, send: Callable): ...
def write_sse(event: ServerSentEvent) -> bytes: ...
def extract_rsgi_headers(raw_headers: Any) -> list[tuple[bytes, bytes]]: ...
def instantiate_rsgi_request(scope: Any, protocol: Any) -> Request: ...
def send_rsgi_response_sync(response: Response, protocol: Any) -> Any: ...
async def send_rsgi_response(response: Response, protocol: Any) -> None: ...

